version: "2"

run:
  timeout: 5m
  skip-dirs:
    - testing
    - pkg/api

linters:
  enable:
    - gosec

issues:
  exclude-rules:
    - path: ".*\\.pb\\.go$"
      linters:
        - all
    - path: ".*/generated/.*\\.go$"  
      linters:
        - all
    - path: "pkg/api/.*\\.go$"
      linters:
        - all