apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - frontend.yaml
  - backend.yaml
  - database.yaml

commonLabels:
  app.kubernetes.io/part-of: three-tier-microservice
  app.kubernetes.io/managed-by: navigator

namespace: microservice-demo