apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - gateway.yaml
  - peerauthentication.yaml
  - external-serviceentry.yaml
  - frontend
  - backend
  - database

commonLabels:
  app.kubernetes.io/part-of: three-tier-microservice
  app.kubernetes.io/managed-by: navigator

namespace: microservices