apiVersion: v1
kind: Namespace
metadata:
  name: microservice-demo
  labels:
    istio-injection: enabled
    app.kubernetes.io/part-of: three-tier-microservice
    app.kubernetes.io/managed-by: navigator