apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml
  - virtualservice.yaml
  - destinationrule.yaml
  - sidecar.yaml
  - peerauthentication.yaml
  - authorizationpolicy.yaml