// Copyright 2025 Navigator Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             (unknown)
// source: backend/v1alpha1/troubleshooting.proto

package v1alpha1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	TroubleshootingService_GetProxyConfig_FullMethodName = "/navigator.backend.v1alpha1.TroubleshootingService/GetProxyConfig"
)

// TroubleshootingServiceClient is the client API for TroubleshootingService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TroubleshootingServiceClient interface {
	// GetProxyConfig returns the proxy configuration for a specific service instance.
	GetProxyConfig(ctx context.Context, in *GetProxyConfigRequest, opts ...grpc.CallOption) (*GetProxyConfigResponse, error)
}

type troubleshootingServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTroubleshootingServiceClient(cc grpc.ClientConnInterface) TroubleshootingServiceClient {
	return &troubleshootingServiceClient{cc}
}

func (c *troubleshootingServiceClient) GetProxyConfig(ctx context.Context, in *GetProxyConfigRequest, opts ...grpc.CallOption) (*GetProxyConfigResponse, error) {
	out := new(GetProxyConfigResponse)
	err := c.cc.Invoke(ctx, TroubleshootingService_GetProxyConfig_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TroubleshootingServiceServer is the server API for TroubleshootingService service.
// All implementations must embed UnimplementedTroubleshootingServiceServer
// for forward compatibility
type TroubleshootingServiceServer interface {
	// GetProxyConfig returns the proxy configuration for a specific service instance.
	GetProxyConfig(context.Context, *GetProxyConfigRequest) (*GetProxyConfigResponse, error)
	mustEmbedUnimplementedTroubleshootingServiceServer()
}

// UnimplementedTroubleshootingServiceServer must be embedded to have forward compatible implementations.
type UnimplementedTroubleshootingServiceServer struct {
}

func (UnimplementedTroubleshootingServiceServer) GetProxyConfig(context.Context, *GetProxyConfigRequest) (*GetProxyConfigResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetProxyConfig not implemented")
}
func (UnimplementedTroubleshootingServiceServer) mustEmbedUnimplementedTroubleshootingServiceServer() {
}

// UnsafeTroubleshootingServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TroubleshootingServiceServer will
// result in compilation errors.
type UnsafeTroubleshootingServiceServer interface {
	mustEmbedUnimplementedTroubleshootingServiceServer()
}

func RegisterTroubleshootingServiceServer(s grpc.ServiceRegistrar, srv TroubleshootingServiceServer) {
	s.RegisterService(&TroubleshootingService_ServiceDesc, srv)
}

func _TroubleshootingService_GetProxyConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetProxyConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TroubleshootingServiceServer).GetProxyConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TroubleshootingService_GetProxyConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TroubleshootingServiceServer).GetProxyConfig(ctx, req.(*GetProxyConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TroubleshootingService_ServiceDesc is the grpc.ServiceDesc for TroubleshootingService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TroubleshootingService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "navigator.backend.v1alpha1.TroubleshootingService",
	HandlerType: (*TroubleshootingServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetProxyConfig",
			Handler:    _TroubleshootingService_GetProxyConfig_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "backend/v1alpha1/troubleshooting.proto",
}
