// Copyright 2025 Navigator Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             (unknown)
// source: frontend/v1alpha1/cluster_registry.proto

package v1alpha1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	ClusterRegistryService_ListClusters_FullMethodName = "/navigator.frontend.v1alpha1.ClusterRegistryService/ListClusters"
)

// ClusterRegistryServiceClient is the client API for ClusterRegistryService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ClusterRegistryServiceClient interface {
	// ListClusters returns sync state information for all connected clusters.
	ListClusters(ctx context.Context, in *ListClustersRequest, opts ...grpc.CallOption) (*ListClustersResponse, error)
}

type clusterRegistryServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewClusterRegistryServiceClient(cc grpc.ClientConnInterface) ClusterRegistryServiceClient {
	return &clusterRegistryServiceClient{cc}
}

func (c *clusterRegistryServiceClient) ListClusters(ctx context.Context, in *ListClustersRequest, opts ...grpc.CallOption) (*ListClustersResponse, error) {
	out := new(ListClustersResponse)
	err := c.cc.Invoke(ctx, ClusterRegistryService_ListClusters_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ClusterRegistryServiceServer is the server API for ClusterRegistryService service.
// All implementations must embed UnimplementedClusterRegistryServiceServer
// for forward compatibility
type ClusterRegistryServiceServer interface {
	// ListClusters returns sync state information for all connected clusters.
	ListClusters(context.Context, *ListClustersRequest) (*ListClustersResponse, error)
	mustEmbedUnimplementedClusterRegistryServiceServer()
}

// UnimplementedClusterRegistryServiceServer must be embedded to have forward compatible implementations.
type UnimplementedClusterRegistryServiceServer struct {
}

func (UnimplementedClusterRegistryServiceServer) ListClusters(context.Context, *ListClustersRequest) (*ListClustersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListClusters not implemented")
}
func (UnimplementedClusterRegistryServiceServer) mustEmbedUnimplementedClusterRegistryServiceServer() {
}

// UnsafeClusterRegistryServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ClusterRegistryServiceServer will
// result in compilation errors.
type UnsafeClusterRegistryServiceServer interface {
	mustEmbedUnimplementedClusterRegistryServiceServer()
}

func RegisterClusterRegistryServiceServer(s grpc.ServiceRegistrar, srv ClusterRegistryServiceServer) {
	s.RegisterService(&ClusterRegistryService_ServiceDesc, srv)
}

func _ClusterRegistryService_ListClusters_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListClustersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClusterRegistryServiceServer).ListClusters(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ClusterRegistryService_ListClusters_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClusterRegistryServiceServer).ListClusters(ctx, req.(*ListClustersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ClusterRegistryService_ServiceDesc is the grpc.ServiceDesc for ClusterRegistryService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ClusterRegistryService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "navigator.frontend.v1alpha1.ClusterRegistryService",
	HandlerType: (*ClusterRegistryServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListClusters",
			Handler:    _ClusterRegistryService_ListClusters_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "frontend/v1alpha1/cluster_registry.proto",
}
