apiVersion: v1
kind: Pod
metadata:
  name: fortio-load
  namespace: microservices
  labels:
    app: fortio-load
    app.kubernetes.io/name: fortio
    app.kubernetes.io/component: load-generator
    app.kubernetes.io/managed-by: navigator
spec:
  containers:
  - name: fortio
    image: fortio/fortio
    args:
    - load
    - -qps
    - "5"               # 5 requests per second
    - -t
    - "0"               # Run indefinitely (until stopped)
    - -c
    - "2"               # Use 2 concurrent connections
    - -keepalive        # Keep connections alive for efficiency
    - -logger-force-color=false  # Disable color for cleaner logs
    - http://istio-ingressgateway.istio-system.svc.cluster.local/proxy/backend:8080/proxy/database:8080
    resources:
      requests:
        memory: "64Mi"
        cpu: "100m"
      limits:
        memory: "128Mi"
        cpu: "200m"
  restartPolicy: OnFailure