apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml
  - virtualservice.yaml
  - destinationrule.yaml

commonLabels:
  app.kubernetes.io/part-of: monolith-application
  app.kubernetes.io/managed-by: navigator