# Navigator microservices deployment configuration
base:
  namespace:
    create: false
    name: default
    labels:
      istio-injection: enabled

  # Default values for all services
  defaults:
    replicaCount: 1
    image:
      repository: ghcr.io/liamawhite/microservice
      pullPolicy: IfNotPresent
      tag: latest
    serviceAccount:
      create: true
      automount: true
    service:
      type: ClusterIP
    resources:
      requests:
        memory: 128Mi
        cpu: 100m
      limits:
        memory: 256Mi
        cpu: 200m
    livenessProbe:
      httpGet:
        path: /health
        port: http
      initialDelaySeconds: 30
      periodSeconds: 10
    readinessProbe:
      httpGet:
        path: /health
        port: http
      initialDelaySeconds: 5
      periodSeconds: 5
    config:
      timeout: 30s
      logLevel: info
      logFormat: json

  # Three-tier services configuration
  services:
    - name: frontend
      config:
        serviceName: frontend
        port: 8080
      service:
        port: 8080
    - name: backend
      config:
        serviceName: backend
        port: 8080
      service:
        port: 8080
    - name: database
      config:
        serviceName: database
        port: 8080
      service:
        port: 8080
