// Copyright 2025 Navigator Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        (unknown)
// source: types/v1alpha1/kubernetes_types.proto

package v1alpha1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ServiceType indicates the type of Kubernetes service.
type ServiceType int32

const (
	// SERVICE_TYPE_UNSPECIFIED indicates the service type is not specified or unknown.
	ServiceType_SERVICE_TYPE_UNSPECIFIED ServiceType = 0
	// CLUSTER_IP exposes the service on a cluster-internal IP.
	ServiceType_CLUSTER_IP ServiceType = 1
	// NODE_PORT exposes the service on each node's IP at a static port.
	ServiceType_NODE_PORT ServiceType = 2
	// LOAD_BALANCER exposes the service externally using a cloud provider's load balancer.
	ServiceType_LOAD_BALANCER ServiceType = 3
	// EXTERNAL_NAME maps the service to the contents of the externalName field.
	ServiceType_EXTERNAL_NAME ServiceType = 4
)

// Enum value maps for ServiceType.
var (
	ServiceType_name = map[int32]string{
		0: "SERVICE_TYPE_UNSPECIFIED",
		1: "CLUSTER_IP",
		2: "NODE_PORT",
		3: "LOAD_BALANCER",
		4: "EXTERNAL_NAME",
	}
	ServiceType_value = map[string]int32{
		"SERVICE_TYPE_UNSPECIFIED": 0,
		"CLUSTER_IP":               1,
		"NODE_PORT":                2,
		"LOAD_BALANCER":            3,
		"EXTERNAL_NAME":            4,
	}
)

func (x ServiceType) Enum() *ServiceType {
	p := new(ServiceType)
	*p = x
	return p
}

func (x ServiceType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ServiceType) Descriptor() protoreflect.EnumDescriptor {
	return file_types_v1alpha1_kubernetes_types_proto_enumTypes[0].Descriptor()
}

func (ServiceType) Type() protoreflect.EnumType {
	return &file_types_v1alpha1_kubernetes_types_proto_enumTypes[0]
}

func (x ServiceType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ServiceType.Descriptor instead.
func (ServiceType) EnumDescriptor() ([]byte, []int) {
	return file_types_v1alpha1_kubernetes_types_proto_rawDescGZIP(), []int{0}
}

var File_types_v1alpha1_kubernetes_types_proto protoreflect.FileDescriptor

var file_types_v1alpha1_kubernetes_types_proto_rawDesc = []byte{
	0x0a, 0x25, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2f, 0x76, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x31,
	0x2f, 0x6b, 0x75, 0x62, 0x65, 0x72, 0x6e, 0x65, 0x74, 0x65, 0x73, 0x5f, 0x74, 0x79, 0x70, 0x65,
	0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x18, 0x6e, 0x61, 0x76, 0x69, 0x67, 0x61, 0x74,
	0x6f, 0x72, 0x2e, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2e, 0x76, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61,
	0x31, 0x2a, 0x70, 0x0a, 0x0b, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x54, 0x79, 0x70, 0x65,
	0x12, 0x1c, 0x0a, 0x18, 0x53, 0x45, 0x52, 0x56, 0x49, 0x43, 0x45, 0x5f, 0x54, 0x59, 0x50, 0x45,
	0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x0e,
	0x0a, 0x0a, 0x43, 0x4c, 0x55, 0x53, 0x54, 0x45, 0x52, 0x5f, 0x49, 0x50, 0x10, 0x01, 0x12, 0x0d,
	0x0a, 0x09, 0x4e, 0x4f, 0x44, 0x45, 0x5f, 0x50, 0x4f, 0x52, 0x54, 0x10, 0x02, 0x12, 0x11, 0x0a,
	0x0d, 0x4c, 0x4f, 0x41, 0x44, 0x5f, 0x42, 0x41, 0x4c, 0x41, 0x4e, 0x43, 0x45, 0x52, 0x10, 0x03,
	0x12, 0x11, 0x0a, 0x0d, 0x45, 0x58, 0x54, 0x45, 0x52, 0x4e, 0x41, 0x4c, 0x5f, 0x4e, 0x41, 0x4d,
	0x45, 0x10, 0x04, 0x42, 0x38, 0x5a, 0x36, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f,
	0x6d, 0x2f, 0x6c, 0x69, 0x61, 0x6d, 0x61, 0x77, 0x68, 0x69, 0x74, 0x65, 0x2f, 0x6e, 0x61, 0x76,
	0x69, 0x67, 0x61, 0x74, 0x6f, 0x72, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x74,
	0x79, 0x70, 0x65, 0x73, 0x2f, 0x76, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x31, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_types_v1alpha1_kubernetes_types_proto_rawDescOnce sync.Once
	file_types_v1alpha1_kubernetes_types_proto_rawDescData = file_types_v1alpha1_kubernetes_types_proto_rawDesc
)

func file_types_v1alpha1_kubernetes_types_proto_rawDescGZIP() []byte {
	file_types_v1alpha1_kubernetes_types_proto_rawDescOnce.Do(func() {
		file_types_v1alpha1_kubernetes_types_proto_rawDescData = protoimpl.X.CompressGZIP(file_types_v1alpha1_kubernetes_types_proto_rawDescData)
	})
	return file_types_v1alpha1_kubernetes_types_proto_rawDescData
}

var file_types_v1alpha1_kubernetes_types_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_types_v1alpha1_kubernetes_types_proto_goTypes = []any{
	(ServiceType)(0), // 0: navigator.types.v1alpha1.ServiceType
}
var file_types_v1alpha1_kubernetes_types_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_types_v1alpha1_kubernetes_types_proto_init() }
func file_types_v1alpha1_kubernetes_types_proto_init() {
	if File_types_v1alpha1_kubernetes_types_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_types_v1alpha1_kubernetes_types_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_types_v1alpha1_kubernetes_types_proto_goTypes,
		DependencyIndexes: file_types_v1alpha1_kubernetes_types_proto_depIdxs,
		EnumInfos:         file_types_v1alpha1_kubernetes_types_proto_enumTypes,
	}.Build()
	File_types_v1alpha1_kubernetes_types_proto = out.File
	file_types_v1alpha1_kubernetes_types_proto_rawDesc = nil
	file_types_v1alpha1_kubernetes_types_proto_goTypes = nil
	file_types_v1alpha1_kubernetes_types_proto_depIdxs = nil
}
