name: hygiene

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]



jobs:
  format:
    name: format
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Install Nix
      uses: cachix/install-nix-action@v25
    
    - name: Check code formatting
      run: make format

    - name: Check dirty 
      run: make dirty

    

  generate:
    name: generate
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Install Nix
      uses: cachix/install-nix-action@v25

    - name: Check generation
      run: make generate

    - name: Check dirty
      run: make dirty
    
