name: test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  unit:
    name: unit
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Install Nix
      uses: cachix/install-nix-action@v25
    
    - name: Run unit tests
      run: make test-unit

  ui:
    name: ui
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Install Nix
      uses: cachix/install-nix-action@v25
    
    - name: Run UI unit tests
      run: make test-ui

  e2e:
    name: e2e
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Install Nix
      uses: cachix/install-nix-action@v25
    
    - name: Install Chromium dependencies manually (temporary workaround)
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          libglib2.0-0 \
          libgobject-2.0-0 \
          libnspr4 \
          libnss3 \
          libnssutil3 \
          libsmime3 \
          libgio-2.0-0 \
          libdbus-1-3 \
          libatk1.0-0 \
          libatk-bridge2.0-0 \
          libcups2 \
          libexpat1 \
          libxcb1 \
          libxkbcommon0 \
          libatspi2.0-0 \
          libx11-6 \
          libxcomposite1 \
          libxdamage1 \
          libxext6 \
          libxfixes3 \
          libxrandr2 \
          libgbm1 \
          libcairo2 \
          libpango-1.0-0 \
          libudev1 \
          libasound2
      
    - name: Run E2E tests
      run: make test-e2e-ci
        
    - name: Upload E2E test results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: playwright-report
        path: ui/e2e/playwright-report/
        retention-days: 30

  release:
    name: release
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    
    - name: Install Nix
      uses: cachix/install-nix-action@v25
    
    - name: Test release build
      run: nix develop --command goreleaser release --snapshot --clean --parallelism 2
